package kd.idp.psidpapp.opt.sys.constant;

public class FieldName {
	//组织机构表字段名
	public static String FIELD_SYS_ORG = "ID,NAME,NICKNAME,PARENTID,PARENTIDS,ICON,ORDERUNITID,CLASS,SORT,DATASTATUSID,CREATEUSERID,CREATETIME,UPDATEUSERID,UPDATETIME,REMARK";
	//用户表字段名
	public static String FIELD_SYS_USER = "ID,NAME,NICKNAME,PSD,ORGID,CLASS,SORT,DATASTATUSID,CREATEUSERID,CREATETIME,UPDATEUSERID,UPDATETIME,REMARK";	
	//角色表字段名
	public static String FIELD_SYS_ROLE = "ID,NAME,NICKNAME,CLASS,SORT,DATASTATUSID,CREATEUSERID,CREATETIME,UPDATEUSERID,UPDATETIME,REMARK";
	//菜单权限表字段名
	public static String FIELD_SYS_MENU = "ID,NAME,NICKNAME,PARENTID,PARENTIDS,ICON,URL,TARGET,PERMISSION,CLASS,SORT,DATASTATUSID,CREATEUSERID,CREATETIME,UPDATEUSERID,UPDATETIME,REMARK";	
	//用户角色关系表字段名
	public static String FIELD_SYS_USER_ROLE = "USERID,ROLEID";	
	//角色权限关系表字段名
	public static String FIELD_SYS_ROLE_MENU = "ROLEID,MENUID";	
	//页号模板表字段名
	public static String FIELD_SYS_PAGENUMBER_PATTERN = "ID,NAME,SERIALCYCLE,SERIALLENGTH,STARTNUM,PAGECONTENT";	
	//页号实例表字段名
	public static String FIELD_SYS_PAGENUMBER_INSTANCE = "PAGEPATTERNID,CURRENTYEAR,CURRENTMONTH,CURRENTDAY,SERIALNUM";	
}
